# Paths
[PATH_CFG]
TUTO_PATH = "D:/Projects/PSC/LLM-DSL-Gen/docs"
REF_PATH = "D:/Projects/PSC/LLM-DSL-Gen/refs"
CHALLENGES_PATH = "D:/Projects/PSC/LLM-DSL-Gen/benchmarks/challenges"
VECTOR_DB_DIR = "D:/Projects/PSC/LLM-DSL-Gen/vector_db"

# Embedding
[EMBEDDING_CFG]
embedding_model = "hf/sentence-transformers/all-mpnet-base-v2"
#embedding_model = openai/text-embedding-3-small
top_k = 5
chunk_size = 500
chunk_overlap = 50

# Model Configuration
[MODEL_CFG]
used_model = "ollama"

[MODEL_CFG.JUDGE]
personality = """Your goal is to judge the correctness of STUDENT ANSWER, as an answer to the QUESTION.\
In order to judge the STUDENT ANSWER, you are given the PROFESSOR ANSWER with a piece of related documentation.\
Your main job is not to check the syntax correctness, but the logical correctness.\
If the STUDENT ANSWER does not treat the QUESTION logically, it is UNACCEPTABLE.\
Pay special attention to the comments in the PROFESSOR ANSWER. If these comments include\
a rule and if the STUDENT ANSWER violates it, this is UNACCEPTABLE.\
If in the show command, the STUDENT ANSWER adds or omits a print position (like a1b2 or a1c3) compared to the PROFESSOR ANSWER, you must ignore this: this is always ACCEPTABLE.\
The use of extra variable or table to temporarily contain a intermediate quantity is ACCEPTABLE.\
Differences in variable names, column names, table names and label names etc. shall systematically be ACCEPTABLE! \
There are sometimes various ways or logics to treat the same QUESTION, and this is ACCEPTABLE, as long as the goal of the QUESTION is achieved.\
Let's think aloud step by step before making your judgement. Tell each ACCEPTABLE or UNACCEPTABLE point. \
At the end of your output, you should judge 0 if there is anything UNACCEPTABLE (even only 1 mark of UNACCEPTABLE) in the STUDENT ANSWER;\
and judge 1 if everything is ACCEPTABLE. End your judgment by the digit either 0 or 1. \
Here is the piece of related documentation : \n ## DOCUMENTATION\n"""

[MODEL_CFG.CODER]
personality = """You are a proficient coder in a Domain Specific Language called Envision. \
Your task is to generate response to the given challenge. \
Some challenges will ask you to generate Envision code,\
others will ask you to explain given code or answer questions related to the Envision language. \
Do not output any intermediate thinking or explanation, only give the final answer.\
Here is the documentation of Envision:\
### Documentation\n"""


# OpenAI Configuration
[MODEL_CFG.OpenAI]
model = "gpt-3.5-turbo"
api_key = "sk-xxxx"
base_url = "https://api.openai.com/v1"

# Ollama Configuration
[MODEL_CFG.Ollama]
model = "deepseek-r1:7b"
api_key = "placeholder"
base_url = "http://localhost:11434/v1"

# DeepSeek Configuration
[MODEL_CFG.DeepSeek]
model = "deepseek-ai/DeepSeek-R1"
api_key = "sk-xxxx"
base_url = "https://api.siliconflow.com/v1"
